<?xml version="1.0"?>

<robot name="left/realsense_d435" xmlns:xacro="http://ros.org/wiki/xacro">
    <!--File includes-->
    <xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/d435.gazebo.xacro"/>

	<xacro:property name="M_PI" value="3.1415926535897931" />

	<!-- The following values are approximate, and the camera node
	publishing TF values with actual calibrated camera extrinsic values -->
	<xacro:property name="d435_cam_depth_to_left_ir_offset"  value="0.0"/>
	<xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
	<xacro:property name="d435_cam_depth_to_color_offset"    value="0.015"/>

	<!-- The following values model the aluminum peripherial case for the
	D435 camera, with the camera joint represented by the actual 
	peripherial camera tripod mount -->
	<xacro:property name="d435_cam_width" 					 value="0.090" />
	<xacro:property name="d435_cam_height" 					 value="0.025" />
	<xacro:property name="d435_cam_depth" 					 value="0.02505" />
	<xacro:property name="d435_cam_mount_from_center_offset" value="0.0149" />

	<!-- The following offset is relative the the physical D435 camera peripherial
	camera tripod mount -->
	<xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
	<xacro:property name="d435_cam_depth_py" value="0.0175"/>
	<xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_base_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_bottom_screw_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_cam_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_depth_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_depth_optical_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_left_ir_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_left_ir_optical_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_right_ir_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_right_ir_optical_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_color_frame_link.xacro" />
	<xacro:include filename="$(find doudou_description)/urdf/urdf_realsense/urdf_d435/d435_color_optical_frame_link.xacro" />

	<xacro:d435_base_link 					prefix="left" />
	<xacro:d435_bottom_screw_frame_link 	prefix="left" />
    <xacro:d435_cam_link 				    prefix="left" />
	<xacro:d435_depth_frame_link            prefix="left" />
	<xacro:d435_depth_optical_frame_link    prefix="left" />
	<xacro:d435_left_ir_frame_link          prefix="left" />
	<xacro:d435_left_ir_optical_frame_link  prefix="left" />
	<xacro:d435_right_ir_frame_link 		prefix="left" />
	<xacro:d435_right_ir_optical_frame_link prefix="left" />
	<xacro:d435_color_frame_link 			prefix="left" />
	<xacro:d435_color_optical_frame_link 	prefix="left" />
 
    <!-- Realsense Gazebo Plugin -->
    <xacro:gazebo_d435 camera_name="d435_left" reference_link="left/d435_cam_link" topics_ns="d435_1" depth_optical_frame="left/d435_depth_optical_frame_link" color_optical_frame="left/d435_color_optical_frame_link" infrared1_optical_frame="left/d435_left_ir_optical_frame_link" infrared2_optical_frame="left/d435_right_ir_optical_frame_link" publish_pointcloud="true"/>

</robot>